Jdp230401 15 Added User entity and UserRepository
piotr-grosicki/project-jdp-2304-01 pull request #17
Opened 2023-04-13 19:35 UTC by RobiBobii

2023-04-13 20:46 UTC, QxaM requested changes
Do usunięcia na pewno wykomentowana część żeby nie zaciemniać kodu - jak jest potrzeba można wrócić do wcześniejszej wersji gitem. Ostatni konstruktor też, bo nic nie wnosi, ustawia to samo co wcześniejszy, tylko ma więcej argumentów.

Adnotacja @GeneratedValue nie działa ze Stringami ([link](https://stackoverflow.com/questions/15466518/how-to-make-string-primary-key-hibernate-generatedvalue-strategies)), a poza tym i tak jest ustawiana ręcznie, a nie generowana + dodatkowo jest ustawiana w konstruktorach, więc moim zdaniem, to albo tu albo w konstruktorach i chyba lepiej jednak w konstruktorach.

Tu już mniejsze i nie trzeba koniecznie - Orders chyba najprościej jednak w Listę - Set zabezpiecza nas głównie przed powtórzeniami, a i tak Baza Danych nie pozwoli nam ustawić dwóch tych samych Order do bazy, bo Id musi być unique.

2023-04-14 11:45 UTC, Mateusz-Surmac commented
Relacja User - Cart chyba lepiej OneToOne. Teoretycznie to nie jest problem, ale wydaje mi się, że jeden koszyk na użytkownika wystarczy. 

Jeśli chodzi o activationKey to metodę generującą klucz, umieścimy w serwisie i będzie wywoływana w controlerze. Lepiej nie zaśmiecać encji. Do tego prościej będzie ustalić ją jako int lub long.

2023-04-14 19:37 UTC, QxaM requested changes
Jeszcze @GeneratedValue nad kluczem - będziemy go generować samemu, nie musi być z automatu.

2023-04-14 19:45 UTC, QxaM approved these changes

2023-04-14 20:23 UTC, Mateusz-Surmac approved these changes

2023-04-14 20:48 UTC, merged