JDP230401-33 v2 - Fix ProductDto
piotr-grosicki/project-jdp-2304-01 pull request #27
Opened 2023-04-20 00:09 UTC by jak-hry

Changes:

ProductDto:
- private ProductGroupDto productGroupDto -> private Long groupId

ProductController:
- cleanUp methods

ProductMapper:
- fixes after changes in the ProductDto class

ProductDbService:
- fixes in deleteProductById method
- adding getGroup method

2023-04-20 20:19 UTC, QxaM requested changes
W DeleteMappingu controller zawsze będzie wyrzucał błąd, jak znadzie i usunie produkt. Powinien wystawiać OK. W Post mappingu fajnie by było zwrócić zapisany produkt - szczególnie, że zwracasz ResponseEntity<ProductDto>, a nie Void.

W mapperze, ProductDbService może być final i inicjalizowany przez @RequiredArgsContrusctor. Poza tym słąbo wygląda wykorzystanie tego serwisu w mapperze, 
chyba lepiej z samego repository skorzystać, a w ogóle może całkiem najlpiej z ProductGroupDto i przemapować mappere (tak jak Cart)

W serwisie w deleteProductById wystarczy tak jak get product jak id - findById.orElseThrow i dalej deleteBy Id.

2023-04-20 21:09 UTC, jak-hry commented
naprawione - https://github.com/piotr-grosicki/project-jdp-2304-01/pull/27/commits/e6d19ab9a2671e6f87c478b357b4a4233a92a89a

2023-04-20 21:49 UTC, Mateusz-Surmac reviewed
W sumie nie jestem pewien czy na pewno do zmiany, ale pytanie czy określasz w metodzie PUT i POST, że dane będą przychodzić w json'ie?  Chodzi mi o dodanie `consumes = MediaType.APPLICATION_JSON_VALUE`

2023-04-20 22:18 UTC, jak-hry commented
Nie określałem z góry w jakim formacie mają przychodzić żądania, więc na wszelki wypadek dodałem - https://github.com/piotr-grosicki/project-jdp-2304-01/pull/27/commits/d021a04f23c2bb5c55ce2d079ba46b1d7312098f

2023-04-21 09:48 UTC, QxaM requested changes
Jedna drobnostka - niepotrzeba "/" w value w mappingach, to sam dodaje już Controller

2023-04-21 10:33 UTC, jak-hry commented
https://github.com/piotr-grosicki/project-jdp-2304-01/pull/27/commits/e432cc3c25dde226095ab69f699c3434c5ba38b7

2023-04-21 10:44 UTC, QxaM approved these changes

2023-04-21 17:36 UTC, RobiBobii approved these changes

2023-04-21 17:54 UTC, merged