JDP230401-25 Added UserMapper, UserDbService
piotr-grosicki/project-jdp-2304-01 pull request #28
Opened 2023-04-20 16:34 UTC by RobiBobii

-Added UserMapper,
-Added UserDbSerive,
-Changed UserRepository,
-Changed UserController

2023-04-20 18:25 UTC, jak-hry requested changes
W UserController brakuje opakowania w ResponceEntity, umożliwi to lepszą kontrolę nad odpowiedziami HTTP.

Dodatkowo w UserDbService brakuje metody generującej losowy klucz ważny godzinę po podaniu poprawnych danych użytkownika.
 Piotr na komunikatorze zarzucił dobrą propozycje jakiego rozwiązania można użyć do stworzenia takiej metody (**.randomUUID()**), więc nie powinno być z tym większych problemów

2023-04-20 20:23 UTC, QxaM requested changes
Dodatkowo - niekoniecznie chcemy za każdym wyświetleniem chcemy wyświetlać ten klucz - wydaje mi się, że tylko przy tworzeniu, potem ma być już schowany, w końcu to klucz.

W Userze będzie potrzeba jeszcze pola z czasem wygenerowania klucza, aby móc sprawdzić tę 1h.

W serwisie zamiast @Autowired lepiej zrobić final przy polu, szczególnie jak masz @RequiredArgsContstructor

2023-04-20 21:30 UTC, Mateusz-Surmac requested changes
Metoda blockUser miała blokować użytkownika, więc wartość status powinna być raczej na false. Brakuje też użycia .save, aby zapisać zmiany w bazie danych.
Potrzebna też jest obsługa wyjątku w deleteUser jeśli użytkownika o danym id nie będzie.

2023-04-21 16:04 UTC, RobiBobii commented
Część poprawiłem ale mam pytanie co do activationKey. Mianowicie możemy użyć metody (.randomUUID()) ale wtedy będzie trzeba zmienić typ na String i pozmieniać w niektórych miejscach zapis danych.

2023-04-21 20:42 UTC, jak-hry approved these changes

2023-04-23 13:40 UTC, Mateusz-Surmac requested changes
blockUser po zmianie statusu na false, nie zapisuje zmiany w bazie danych. I to chyba będzie wszystko

2023-04-23 16:59 UTC, Mateusz-Surmac approved these changes

2023-04-23 17:30 UTC, jak-hry approved these changes

2023-04-23 19:17 UTC, QxaM requested changes
Dodatkowo widzę, że moje wcześniejsze komentarze są nie wzięte za bardzo pod uwagę. Jest zrobione to na longach i mamy masę kodu, który musi to obsłużyć - sprawdzenie znaków, zakresów i randomów. Dodatkowo nie mamy żadnej gwarancji, że generowane kody będą unikalne. Wykorzystanie UUID moim zdaniem nadal jest najszybsze i najprostsze, trzeba będzie tylko wykonać drobną modyfikację testów pod pola UUID. Spring zajmuje się konwersją UUID na stringa, więc tym również się nie zajmujemy.

Nadal wyświetlamy klucz przy każdym wyświetlaniu użytkownika - moim zdaniem również niepoprawnie, każde zapytanie o Usera będzie wyciekało jego klucz.

Nie sprawdzamy nigdzie tej 1h wygenerowanego klucza - moim zdaniem można by to zrobić w metodzie do tworzenia nowego klucza, jeżeli istniejący klucz nie jest "przeterminowany" to po prostu wyświetlamy stary klucz. W przeciwnym razie tworzymy nowy klucz.

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    }
Mapowanie z listy na listę powinno być w mapperze. Dodatkowo nie dodajemy nazwy funkcji (tutaj getAll) do endointu - jeżeli wpiszemy metodę get v1/shop/users to jest jasne, że dostajemy listę. Dodatkowo w polu value nie potrzeba "/"

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        User user = userDbService.getUser(id).orElseThrow(UserNotFoundException::new);
Serwis powinien wyrzucać exception, bo to on przeszukuje bazę danych i tam może pójść coś nie tak. 

Dodatkowo j.w. - nie potrzeba ani "/" ani powtórzonego "get", korzystamy już z metody GET.

Przy pathVaraiable, nie potrzeba też "id"

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    @PostMapping(value = "/add", consumes = MediaType.APPLICATION_JSON_VALUE)
Zasadniczo nie potrzeba w ogóle value tutaj, dodatkowo jak już dodajesz to mieszasz - raz wpisujesz value =, raz nie.

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
Skoro wszędzie jest ResponseEntity.ok() to też bym się tego tutaj trzymał

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        User user = userDbService.getUser(id).orElseThrow(UserNotFoundException::new);
Jak wyżej, nie potrzeba "id" przy pathVariable. Sewis powinen wyrzucić wyjątek. Dodatkowo endpoint "status" mało mówi o tym co robi funkcja - nazwałbym to coś w stylu block, wtedy jest jasne, że blokujemy.

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        User savedUser = userDbService.saveUser(user);
Wszystko powyżej powinien zrobić serwis nie kontroler, czyli odczyt Usera, zmiana jego valuie i zapis do DB - po to jest.

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/domain/User.java
Kolumny nazywamy zazwyczaj wielkimi literami, słowa oddzielamy znakiem '_'

2023-04-23 19:17 UTC, QxaM commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +    }
Czy ta metoda jest gdziekolwiek używana? Bo tak na szybko nie widzę, dodatkowo dodaje długą metodę do repozytorium, której wygląda, że nie potrzebujemy.

2023-04-24 03:26 UTC, closed without merging